# Generated by Django 5.2.6 on 2025-12-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('available_text', models.CharField(blank=True, help_text="Optional: e.g., 'June–August 2025' or 'Flexible'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='sublease_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subleases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubleasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sublease_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sublease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sublease.sublease')),
            ],
        ),
    ]
