# Generated by Django 5.2.6 on 2025-12-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtracker',
            name='deadline',
        ),
    ]
